[package]
name = "kernel"
version = "0.1.0"
authors = ["Emad Salim <esalim@mun.ca>"]

[lib]
crate-type = ["staticlib"]

[dependencies]
multiboot2 = "0.1.0"
rlibc = "0.1.4"
spin = "0.4.5"
bitflags = "0.9.0"

[profile.release]
panic = "abort"